require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BusinessEmployeesController do

  # This should return the minimal set of attributes required to create a valid
  # BusinessEmployee. As you add validations to BusinessEmployee, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BusinessEmployeesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all business_employees as @business_employees" do
      business_employee = BusinessEmployee.create! valid_attributes
      get :index, {}, valid_session
      assigns(:business_employees).should eq([business_employee])
    end
  end

  describe "GET show" do
    it "assigns the requested business_employee as @business_employee" do
      business_employee = BusinessEmployee.create! valid_attributes
      get :show, {:id => business_employee.to_param}, valid_session
      assigns(:business_employee).should eq(business_employee)
    end
  end

  describe "GET new" do
    it "assigns a new business_employee as @business_employee" do
      get :new, {}, valid_session
      assigns(:business_employee).should be_a_new(BusinessEmployee)
    end
  end

  describe "GET edit" do
    it "assigns the requested business_employee as @business_employee" do
      business_employee = BusinessEmployee.create! valid_attributes
      get :edit, {:id => business_employee.to_param}, valid_session
      assigns(:business_employee).should eq(business_employee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BusinessEmployee" do
        expect {
          post :create, {:business_employee => valid_attributes}, valid_session
        }.to change(BusinessEmployee, :count).by(1)
      end

      it "assigns a newly created business_employee as @business_employee" do
        post :create, {:business_employee => valid_attributes}, valid_session
        assigns(:business_employee).should be_a(BusinessEmployee)
        assigns(:business_employee).should be_persisted
      end

      it "redirects to the created business_employee" do
        post :create, {:business_employee => valid_attributes}, valid_session
        response.should redirect_to(BusinessEmployee.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved business_employee as @business_employee" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessEmployee.any_instance.stub(:save).and_return(false)
        post :create, {:business_employee => {}}, valid_session
        assigns(:business_employee).should be_a_new(BusinessEmployee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessEmployee.any_instance.stub(:save).and_return(false)
        post :create, {:business_employee => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested business_employee" do
        business_employee = BusinessEmployee.create! valid_attributes
        # Assuming there are no other business_employees in the database, this
        # specifies that the BusinessEmployee created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BusinessEmployee.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => business_employee.to_param, :business_employee => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested business_employee as @business_employee" do
        business_employee = BusinessEmployee.create! valid_attributes
        put :update, {:id => business_employee.to_param, :business_employee => valid_attributes}, valid_session
        assigns(:business_employee).should eq(business_employee)
      end

      it "redirects to the business_employee" do
        business_employee = BusinessEmployee.create! valid_attributes
        put :update, {:id => business_employee.to_param, :business_employee => valid_attributes}, valid_session
        response.should redirect_to(business_employee)
      end
    end

    describe "with invalid params" do
      it "assigns the business_employee as @business_employee" do
        business_employee = BusinessEmployee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessEmployee.any_instance.stub(:save).and_return(false)
        put :update, {:id => business_employee.to_param, :business_employee => {}}, valid_session
        assigns(:business_employee).should eq(business_employee)
      end

      it "re-renders the 'edit' template" do
        business_employee = BusinessEmployee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessEmployee.any_instance.stub(:save).and_return(false)
        put :update, {:id => business_employee.to_param, :business_employee => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested business_employee" do
      business_employee = BusinessEmployee.create! valid_attributes
      expect {
        delete :destroy, {:id => business_employee.to_param}, valid_session
      }.to change(BusinessEmployee, :count).by(-1)
    end

    it "redirects to the business_employees list" do
      business_employee = BusinessEmployee.create! valid_attributes
      delete :destroy, {:id => business_employee.to_param}, valid_session
      response.should redirect_to(business_employees_url)
    end
  end

end
